name: gracieusgalerij
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_database: ^10.5.4
  firebase_core: ^2.30.1
  shimmer_animation: ^2.1.0+1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  path: ^1.9.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.6.1
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  flutter_config: ^2.0.2
  flutter_inner_shadow: ^0.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - fonts/
  
  fonts:
    - family: Belgrano
      fonts:
      - asset: fonts/Belgrano-Regular.ttf
    - family: Bebas Neue
      fonts:
      - asset: fonts/BebasNeue-Regular.ttf
    - family: Itim
      fonts:
      - asset: fonts/Itim-Regular.ttf
    - family: Basic
      fonts:
      - asset: fonts/Basic-Regular.ttf
    - family: Battambang
      fonts:
      - asset: fonts/Battambang-Regular.ttf
    - family: Bayon
      fonts:
      - asset: fonts/Bayon-Regular.ttf
    - family: Bellefair
      fonts:
      - asset: fonts/Itim-Regular.ttf
    - family: BlackOpsOne
      fonts:
      - asset: fonts/BlackOpsOne-Regular.ttf
    - family: OdorMeanChey
      fonts:
      - asset: fonts/OdorMeanChey-Regular.ttf
    - family: PragatiNarrow
      fonts:
      - asset: fonts/PragatiNarrow-Regular.ttf