// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_sQTXNxI5TcHAjFjHrXfrjcCNiUGuBBs',
    appId: '1:743602971084:web:254b2dfd7000d592673d69',
    messagingSenderId: '743602971084',
    projectId: 'gracieusg',
    authDomain: 'gracieusg.firebaseapp.com',
    storageBucket: 'gracieusg.appspot.com',
    measurementId: 'G-H21Z44JM5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihVpb2KwRCR9ItAbdj4SWuuVW50sWbK8',
    appId: '1:743602971084:android:d52e95ca804970dc673d69',
    messagingSenderId: '743602971084',
    projectId: 'gracieusg',
    storageBucket: 'gracieusg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxFDDNmRYv2_BtWI_-zzJV93T07q8cryk',
    appId: '1:743602971084:ios:9f0692e339f1b8e3673d69',
    messagingSenderId: '743602971084',
    projectId: 'gracieusg',
    storageBucket: 'gracieusg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxFDDNmRYv2_BtWI_-zzJV93T07q8cryk',
    appId: '1:743602971084:ios:9f0692e339f1b8e3673d69',
    messagingSenderId: '743602971084',
    projectId: 'gracieusg',
    storageBucket: 'gracieusg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_sQTXNxI5TcHAjFjHrXfrjcCNiUGuBBs',
    appId: '1:743602971084:web:63ae02622e52a66b673d69',
    messagingSenderId: '743602971084',
    projectId: 'gracieusg',
    authDomain: 'gracieusg.firebaseapp.com',
    storageBucket: 'gracieusg.appspot.com',
    measurementId: 'G-XMR1K47J9N',
  );
}
